networks:
  network:  # Define the network
    ipam:
      driver: default
      config:
        - subnet: 14.0.0.0/24  # Define the subnet for the custom network

services:
  database-postgresql:
    build:
      dockerfile: ./docker/database-postgresql/Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '${POSTGRES_PUBLIC_PORT}:${POSTGRES_PORT}'
    networks:
      network:
        ipv4_address: ${POSTGRES_PUBLIC_HOST}

  api-chi:
    build:
      dockerfile: ./docker/api-chi/Dockerfile
    environment:
      # Database
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_PUBLIC_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}

      # Auth
      AUTH_USERNAME: ${API_CHI_AUTH_USERNAME}
      AUTH_PASSWORD: ${API_CHI_AUTH_PASSWORD}
      AUTH_BCRYPT_COST: ${API_CHI_AUTH_BCRYPT_COST}

      # Api
      API_PORT: ${API_CHI_PORT}

      # Web
      WEB_HOST: ${LOCALHOST}
      WEB_PORT: ${WEB_NEXT_PUBLIC_PORT}
    ports:
      - '${API_CHI_PUBLIC_PORT}:${API_CHI_PORT}'
    networks:
      network:
        ipv4_address: ${API_CHI_PUBLIC_HOST}

  web-next:
    build:
      dockerfile: ./docker/web-next/Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - '${WEB_NEXT_PUBLIC_PORT}:3000'