name: Github Actions
run-name: ${{ github.actor }} is running Github Actions 🚀
on:
  push:
    branches:
      - '*'

jobs:
  build-docker:
    name: Build docker
    runs-on: ubuntu-24.04

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup Docker, Docker compose and build start
      uses: hoverkraft-tech/compose-action@v2.0.1

  enter-nix-shell:
    name: Enter nix shell
    runs-on: ubuntu-24.04

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup nix
      uses: cachix/install-nix-action@v27

    - name: Enter nix flake devshell
      run: nix develop .
      if: always()

  test-auth-api-docker:
    name: Build and test auth api docker
    runs-on: ubuntu-24.04
    needs: [ build-docker ]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup Docker, Docker compose and build start
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        services:
          api-chi

    - name: Test api-chi auth service
      run: sh scripts/test.bash api-auth-service

    - name: Test api-chi auth middleware
      run: sh scripts/test.bash api-auth-middleware

    - name: Test api-chi auth route
      run: sh scripts/test.bash api-auth-route
